[33mWARNING [0m charms.loki_k8s.v1.loki_push_api:loki_push_api.py:2499 Juju version 0.0.0 does not support Pebble log forwarding. Juju >= 3.4 is needed.
[33mWARNING [0m charms.loki_k8s.v1.loki_push_api:loki_push_api.py:2649 No Loki endpoints available
[31m[1mERROR   [0m root:charm.py:175 failed to stop maubot
Traceback (most recent call last):
  File "/home/runner/work/maubot-operator/maubot-operator/src/charm.py", line 162, in _reconcile
    self._configure_maubot()
  File "/home/runner/work/maubot-operator/maubot-operator/src/charm.py", line 149, in _configure_maubot
    config["database"] = self._get_postgresql_credentials()
  File "/home/runner/work/maubot-operator/maubot-operator/src/charm.py", line 389, in _get_postgresql_credentials
    raise MissingRelationDataError(
charm.MissingRelationDataError: No postgresql relation data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/maubot-operator/maubot-operator/src/charm.py", line 166, in _reconcile
    self.container.stop(MAUBOT_NAME)
  File "/home/runner/work/maubot-operator/maubot-operator/.tox/integration/lib/python3.10/site-packages/ops/model.py", line 2699, in stop
    self._pebble.stop_services(service_names)
  File "/home/runner/work/maubot-operator/maubot-operator/.tox/integration/lib/python3.10/site-packages/ops/_private/harness.py", line 3291, in stop_services
    raise self._api_error(400, f'cannot stop services: service {name} does not exist')
ops.pebble.APIError: cannot stop services: service maubot does not exist
[32mINFO    [0m charms.data_platform_libs.v0.data_interfaces:data_interfaces.py:3861 database created at 2025-10-28 11:40:10.155566
[33mWARNING [0m root:charm.py:419 no matrix-auth relation found, getting default matrix credentials